name = "chip8"
description = "A simple CHIP-8 emulator."
version = "0.1.0-dev"

authors = ["moehr1z"]
maintainers = ["moehr1z <mooehr1z@gmail.com>"]
licenses = "MIT"
website = ""
tags = []

[build-switches]
"*".style_checks = "No"
"*".ada_Version = "Ada2022"
development.runtime_checks = "Everything"
development.contracts = "Yes"
release.runtime_checks = "None"

[[depends-on]]
sdlada = "^2.5.20"

[[depends-on]]
gnatprove = "^13.2.1"
